name: Vue CLI CI/CD (self-hosted build)

on:
  push:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: frontend-master
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Create .env
        run: |
          cat > .env << 'EOF'
          ${{ secrets.PROD_ENV_FILE }}
          EOF

      - name: Install deps
        run: npm ci --prefer-offline --no-audit --progress=false

      - name: Build (lower footprint)
        env:
          NODE_ENV: production
          
        run: |
          nice -n 10 ionice -c2 -n7 npx vue-cli-service build

      - name: Deploy with rsync
        run: |
          sudo mkdir -p /var/www/html
          sudo rsync -a --delete dist/ /var/www/html/
