name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Crear .env
        run: |
          cat > .env << 'EOF'
          ${{ secrets.PROD_ENV_FILE }}
          EOF

      - run: npm ci
      - run: npm run build --if-present
      - run: sudo cp -r /home/ubuntu/actions-runner/_work/crm-frontend/crm-frontend/dist/* /var/www/html/
